15 lists
AlexandraPoturaeva/learn_python pull request #4
Opened 2022-08-30 07:48 UTC by AlexandraPoturaeva

**15.1 Списки и их инициализация**

**Задача 1. Таблица степеней**
Аркадий как-то раз написал программу для вывода таблицы степеней для определённых чисел. Недавно он узнал про такую штуку, как списки, и решил программу немного переписать, а заодно усовершенствовать её. По его задумке, вначале есть всего три числа: 3, 7 и 5, а затем с помощью бесконечного цикла программа запрашивает новое число, закидывает его в конец текущего списка чисел и выводит вторую, третью и четвёртую степень каждого числа текущего списка. Вот какая программа получилась у Аркадия:
![image](https://user-images.githubusercontent.com/112418003/187380065-9d4adb1a-b595-4f2d-b7de-b171acd702e5.png)

Однако, к сожалению, эта программа у него не заработала. Помогите Аркадию исправить ошибки в коде. Убедитесь, что программа работает верно.

Пример верного результата:
Новое число: 1
Текущий список чисел: [3, 7, 5, 1]
9 27 81
49 343 2401
25 125 625
1 1 1

Новое число: 2
Текущий список чисел: [3, 7, 5, 1, 2]
9 27 81
49 343 2401
25 125 625
1 1 1
4 8 16

**Задача 2. Очень простая задача**
У вас есть список numbers. Напишите программу, которая заполняет список числами от 0 до 100 и выводит его на экран.

**Задача 3. Контроль**
В любой компании есть список сотрудников. Руководство одной компании хочет знать, на рабочем месте ли сейчас сотрудник. У каждого сотрудника есть пропуск со своим ID-номером (это положительное число), список активных пропусков сотрудников известен заранее.

Напишите программу, которая сначала запрашивает у пользователя количество сотрудников в офисе, ID их пропусков, а затем запрашивает ID пропуска, который нужно найти в этом списке. Если такой есть, то вывести «Сотрудник на месте», а иначе «Сотрудник не работает!».
 
Пример:
Кол-во сотрудников в офисе: 4
ID сотрудника: 10
ID сотрудника: 20
ID сотрудника: 30
ID сотрудника: 40
Какой ID ищем? 35
Сотрудник не работает!

2022-08-30 11:28 UTC, AlexandraPoturaeva commented
**15.2 Индексы. Работа с элементами списка**

**Задача 1. Гугл**
Программисты постоянно гуглят ошибки и ищут уже готовый код, который можно использовать для своей программы, чтобы не изобретать велосипед. Андрей поступил также и нашёл для своего проекта код, который должен находить минимальное и максимальное числа в списке. Вот этот код:
![image](https://user-images.githubusercontent.com/112418003/187425166-03e59d8a-c9ea-471c-bcb8-de62b161c1e4.png)

Однако он столкнулся с проблемой. Если брать, к примеру, количество чисел 5, то на тестах -1 -2 -3 -4 -5 и 1 2 3 4 5 программа выводит неверный результат. 

Доработайте программу так, чтобы она выводила верный результат. Подсказка: для отладки используйте точки останова.

Задача 2. Кратность
Пользователь вводит список из N чисел и число K. Напишите код, выводящий на экран сумму индексов элементов списка, которые кратны K.

Пример:
Кол-во чисел в списке: 4
Введите 1 число: 1
Введите 2 число: 20
Введите 3 число: 30
Введите 4 число: 4
 
Введите делитель: 10

Индекс числа 20: 1
Индекс числа 30: 2
Сумма индексов: 3

**Задача 3. Собачьи бега**
В собачьих бегах участвует N собак, у каждой из них есть определённое количество очков за сезон. На огромном табло выводятся очки каждой собаки. Однако при выводе был обнаружен баг: собаки с наибольшим и наименьшим количеством очков поменялись местами! Нужно это исправить.

Дан список очков из N собак. Напишите программу, которая меняет местами наибольший и наименьший элементы в списке.

2022-08-31 19:04 UTC, dimastaja commented on 15_lists.py
> +#     numbers.append(number)
все инпуты надо делать рандомом. Даже если условие просит сделать ввод и даже если в уже данном коде есть инпут. ВСЕГДА надо заменять на рандом, никакой ручной работы при тестировании быть не должно

2022-08-31 19:10 UTC, dimastaja commented on 15_lists.py
> +#
И еще, если уж так делать, то при выполнении условия из цикла нужно выходить (ибо зачем дальше обходить его)

2022-08-31 19:12 UTC, dimastaja commented on 15_lists.py
> +#
Аналогично предыдущей задачи. Никаких инпутов, только рандомы

2022-08-31 19:14 UTC, dimastaja commented on 15_lists.py
> +#
Здесь у тебя одинаковые циклы, достаточно одного (как и в задаче). Начальные значения могут быть, например, первым элементом массива. Почитай про DRY принцип в гугле. И еще - программисты любят, когда кода мало.

2022-08-31 19:16 UTC, dimastaja commented on 15_lists.py
> +
Это хорошо)

2022-08-31 19:18 UTC, dimastaja commented on 15_lists.py
> +
в целом норм, но юзай таки функцию index. вот это вот циклы, когда надо найти элемент в списке - смотрятся криво.

2022-08-31 19:20 UTC, dimastaja commented on 15_lists.py
> +#
Как можно сгенерить 
1) генеришь рандомом количество слов
2) пишешь функцию, которая генерит случайное слово - погугли, как это сделать, либо со мной вслух проговори
3) в цикле делаешь соединение слов и двоеточий

2022-08-31 19:23 UTC, dimastaja commented on 15_lists.py
> +
норм, но условие какое-то сложноватое получилось

2022-08-31 19:24 UTC, dimastaja commented on 15_lists.py
> +
норм, но надо генерить слова. Вводить - очень долго всегда. Если не хочется генерить случайным образом- можно сразу создавать готовые списки и их юзать. Для тестов можно создавать несколько разных списков заранее

2022-09-01 06:56 UTC, AlexandraPoturaeva commented on 15_lists.py
> +#     numbers.append(number)
добавила рандом и изменила бесконечный цикл (с True) на цикл с рандомом (завершить/продолжить).

2022-09-01 06:57 UTC, AlexandraPoturaeva commented on 15_lists.py
> +#
добавила решение задачи вторым методом - с индексом

2022-09-01 07:10 UTC, AlexandraPoturaeva commented on 15_lists.py
> +#
Добавила решения задачи ещё двумя методами. 
1 - исправила цикл
2 - использовала функции min() и max()

2022-09-01 13:37 UTC, AlexandraPoturaeva commented on 15_lists.py
> +
попробовала с index, но получилось, наверное, тоже как-то кривовато. Пока лучше не придумала

2022-09-01 15:22 UTC, AlexandraPoturaeva commented on 15_lists.py
> +
Упростила условие

2022-09-02 10:45 UTC, AlexandraPoturaeva commented
**15.6 Практическая работа**

**Задача 1. Генерация списка**
Что нужно сделать
Дано целое число N. Напишите программу, которая формирует список из нечётных чисел от одного до N.

Пример 1:
Введите число: 1
Список из нечётных чисел от одного до N: [1]

Пример 2:
Введите число: 14
Список из нечётных чисел от одного до N: [1, 3, 5, 7, 9, 11, 13]

**Задача 2. Турнир**
Что нужно сделать
Для соревнований по волейболу необходимо сформировать турнирнирную сетку из восьми человек на два дня. На первый день из списка участников решили выбрать каждого второго.
Дан список из восьми имён: Артемий, Борис, Влад, Гоша, Дима, Евгений, Женя, Захар. Напишите программу, которая выводит элементы списка только с чётными индексами.

Пример:
Первый день: ['Артемий', 'Влад', 'Дима', 'Женя']

**Задача 3. Клетки**
Что нужно сделать
В научной лаборатории выводят и тестируют новые виды клеток. Есть список из N этих клеток, элементом которого является показатель эффективности, а индексом — ранг клетки. Учёные отбирают клетки по следующему принципу: если эффективность клетки меньше её ранга, то она не подходит.
Напишите программу, которая выводит на экран элементы списка, значения которых меньше их индекса.

Пример:
Количество клеток: 5
Эффективность 1 клетки: 3
Эффективность 2 клетки: 0
Эффективность 3 клетки: 6
Эффективность 4 клетки: 2
Эффективность 5 клетки: 10

Неподходящие значения: 0 2

**Задача 4. Видеокарты**
Что нужно сделать
В базе магазина электроники есть список видеокарт компании NVIDIA разных поколений. Вместо полных названий хранятся только числа, которые обозначают модель и поколение видеокарты. Недавно компания выпустила новую линейку видеокарт. Самые старшие поколения разобрали за пару дней.
Напишите программу, которая удаляет из списка видеокарт наибольшие элементы.

Пример:
Количество видеокарт: 5
1 Видеокарта: 3070
2 Видеокарта: 2060
3 Видеокарта: 3090
4 Видеокарта: 3070
5 Видеокарта: 3090

Старый список видеокарт: [ 3070 2060 3090 3070 3090 ]
Новый список видеокарт: [ 3070 2060 3070 ]

**Задача 5. Кино**
Что нужно сделать
Илья зашёл на любительский киносайт, на котором пользователи оставляют рецензии на фильмы. Их список:
films = [‘Крепкий орешек’, ‘Назад в будущее’, ‘Таксист’, ‘Леон’, ‘Богемская рапсодия’, ‘Город грехов’, ‘Мементо’, ‘Отступники’, ‘Деревня’]
Илья на сайте в первый раз. Он хочет зарегистрироваться и сразу добавить часть фильмов в список любимых, чтобы позже прочитать рецензии на них.
Напишите программу, в которой пользователь вводит фильм. Если он есть в перечне, то добавляется в список любимых. Если его нет, то выводится ошибка. В конце выведите весь список любимых фильмов.

Пример:
Сколько фильмов хотите добавить? 3
Введите название фильма: Леон
Введите название фильма: Безумный Макс
Ошибка: фильма Безумный Макс у нас нет :(
Введите название фильма: Мементо
Ваш список любимых фильмов: Леон, Мементо

**Задача 6. Анализ слова**
Что нужно сделать
Напишите программу — анализатор слов, чтобы использовать её для тренировки нейросети и генерировать нужный текст.
Пользователь вводит слово. Напишите программу, которая считает количество уникальных букв в слове. Уникальные буквы — это те, которые встречаются всего один раз.

Пример 1:
Введите слово: привет
Количество уникальных букв: 6

Пример 2:
Введите слово: лава
Количество уникальных букв: 2

**Задача 7. Контейнеры**
Что нужно сделать
Контейнеры на складе лежат в ряд в порядке невозрастания (меньше либо равно) массы в килограммах. На склад привезли ещё один контейнер, который тоже нужно положить на определённое место.
Напишите программу, которая получает на вход невозрастающую последовательность натуральных чисел. Они означают массу каждого контейнера в ряду. После этого вводится число X — масса нового контейнера. Программа выводит номер, под которым будет лежать новый контейнер. Если в ряде есть контейнеры с массой, как у нового, то его нужно положить после них.
Обеспечьте контроль ввода: все числа не превышают 200.

Пример:
Количество контейнеров: 8
Введите вес контейнера: 165
Введите вес контейнера: 163
Введите вес контейнера: 160
Введите вес контейнера: 160
Введите вес контейнера: 157
Введите вес контейнера: 157
Введите вес контейнера: 155
Введите вес контейнера: 154

Введите вес нового контейнера: 162

Номер, который получит новый контейнер: 3

**Задача 8. Бегущие цифры**
Что нужно сделать
Вы пишете программу для маленького табло, в котором циклически повторяется один и тот же текст или числа. Например, как в метро, автобусах или трамваях.
Даны список из N элементов и целое число K. Напишите программу, которая циклически сдвигает элементы списка вправо на K позиций. Используйте минимально возможное количество операций присваивания.

Пример 1:
Сдвиг: 1
Изначальный список: [1, 2, 3, 4, 5]
Сдвинутый список: [5, 1, 2, 3, 4]

Пример 2:
Сдвиг: 3
Изначальный список: [1, 4, -3, 0, 10]
Сдвинутый список: [-3, 0, 10, 1, 4]

**Задача 9. Анализ слова 2**
Что нужно сделать
Продолжите писать анализаторы для текста. Теперь необходимо реализовать код, с помощью которого можно определять палиндромы. То есть нужно находить слова, которые одинаково читается слева направо и справа налево.

Напишите такую программу.

Пример 1:
Введите слово: мадам
Слово является палиндромом

Пример 2:
Введите слово: abccba
Слово является палиндромом

Пример 3:
Введите слово: abbd
Слово не является палиндромом

**Задача 10. Сортировка**
Что нужно сделать
Дан список из N чисел. Напишите программу, которая сортирует элементы списка по возрастанию и выводит их на экран. Дополнительный список нельзя использовать.
Постарайтесь придумать и написать как можно более эффективный алгоритм сортировки.

Пример:
Изначальный список: [1, 4, -3, 0, 10]
Отсортированный список: [-3, 0, 1, 4, 10]

2022-09-02 12:28 UTC, dimastaja commented on 15_lists.py
> +#     numbers.append(number)
Саш, оставлять закомментированные строчки, вместо которых уже есть новые не надо. У тебя все история есть в 1) local history 
2) в git history

2022-09-02 12:30 UTC, dimastaja commented on 15_lists.py
> +#
Необходимо вынести создание рандомного слова в отдельную функцию. В дальнейшем она тебе точно пригодится

2022-09-18 08:04 UTC, dimastaja approved these changes

2022-09-18 08:04 UTC, dimastaja commented on 15_lists.py
> +# if len(favor_films) > 0:
это кривовато. Пустой массив проверять надо просто
```suggestion
# if favor_films:
```
см. https://stackoverflow.com/questions/53513/how-do-i-check-if-a-list-is-empty

2022-09-18 08:12 UTC, dimastaja commented on 15_lists.py
> +#
Это точно можно упростить. 
Куча способов, как избежать двух циклов, хватит одного цикла. Переделывать не надо, просто поприкидывай сама, что можно сделать, ну и вот это почитай
https://pythobyte.com/python-count-unique-values-in-list-346c1a17/

2022-09-18 08:26 UTC, dimastaja requested changes
fix

2022-09-18 19:23 UTC, merged