16. Методы для работы со списками
AlexandraPoturaeva/learn_python pull request #5
Opened 2022-09-06 09:44 UTC by AlexandraPoturaeva

**16.2 Работа со списками: методы insert, remove, index**

**Задача 1. Зоопарк**
В маленьком зоопарке каждое животное сидит в отдельной клетке, всего этих животных четверо: лев, кенгуру, слон и обезьяна. В базе данных они хранятся в виде вот такого списка:

zoo = ['lion', 'kangaroo', 'elephant', 'monkey']

Сегодня в зоопарк завезли медведя (bear) и посадили его между львом и кенгуру. В итоге животных стало пять. А через неделю слона перевезли в другое место и в списке снова стало четверо животных.

Реализуйте эти действия в коде программы и выведите в консоль итоговый список животных, а также покажите, в какой клетке сидят лев и обезьяна. Для этого используйте методы списков.

Результат работы программы:
Зоопарк: ['lion', 'bear', 'kangaroo', 'monkey']
Лев сидит в клетке номер 1
Обезьяна сидит в клетке номер 4

**Задача 2. Сокращения**
В одной компании наступили «тёмные времена», и сотрудников стали сокращать. Зарплаты сотрудников хранятся в списке из N этих самых зарплат. Зарплаты уже уволенных сотрудников обозначаются в списке числом 0.

Напишите программу, которая запрашивает у пользователя количество сотрудников и их зарплаты, затем удаляет все элементы списка со значением 0 и выводит в консоль, сколько сотрудников осталось, а также их зарплаты. Дополнительный список использовать нельзя.
 
Пример:
Кол-во сотрудников: 7
Зарплата 1 сотрудника: 10000
Зарплата 2 сотрудника: 25000
Зарплата 3 сотрудника: 0
Зарплата 4 сотрудника: 50000
Зарплата 5 сотрудника: 60000
Зарплата 6 сотрудника: 0
Зарплата 7 сотрудника: 17000

Осталось сотрудников: 5
Зарплаты: [10000, 25000, 50000, 60000, 17000]

Дополнительно: выведите на экран максимальную и минимальную зарплату оставшихся сотрудников. Для этого используйте функции max и min. Да, те самые, которыми нельзя называть переменные. В скобках функций просто укажите список.

Пример:
Максимальная зп: 60000
Минимальная зп: 10000

**Задача 3. Кино**
Мы поддерживаем свой киносайт и хотим сделать так, чтобы пользователи после регистрации могли создать собственный рейтинг фильмов из тех, которые есть на сайте. Вот сам список фильмов (конечно же, можете брать свои):

films = [
    'Крепкий орешек', 'Назад в будущее', 'Таксист', 
    'Леон', 'Богемская рапсодия', 'Город грехов',
    'Мементо', 'Отступники', 'Деревня', 
    'Проклятый остров', 'Начало', 'Матрица'
]

Напишите программу, которая позволяет добавлять в свой рейтинг фильмы, удалять их оттуда, а также вставлять на нужное пользователю место. Обеспечьте контроль ввода и сделайте так, чтобы в список нельзя было добавить один и тот же фильм несколько раз.

Пример:
Ваш текущий топ фильмов: []
Название фильма: Леон
Команды: добавить, вставить, удалить
Введите команду: добавить

Ваш текущий топ фильмов: [‘Леон’]
Название фильма: Леон
Команды: добавить, вставить, удалить
Введите команду: добавить
Этот фильм уже есть в вашем списке.

Ваш текущий топ фильмов: [‘Леон’]
Название фильма: Матрица
Команды: добавить, вставить, удалить
Введите команду: добавить

Ваш текущий топ фильмов: [‘Леон’, ‘Матрица’]
Название фильма: Леон
Команды: добавить, вставить, удалить
Введите команду: удалить

Ваш текущий топ фильмов: [‘Матрица’]
Название фильма: …..

**16.3 Работа с несколькими списками. Методы extend и count**

**Задача 1. Задачи компаний**
Одна IT-компания решила расшириться и взяла под своё крыло ещё три таких же, но поменьше. Конечно же, все выполненные и невыполненные задачи этих компаний перетекли в основную компанию.

Даны четыре списка компаний, в которых для каждой задачи написано, выполнена (1) она или нет (0):

main = [1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1]
first_company = [0, 0, 0]
second_company = [1, 0, 0, 1, 1]
third_company = [1, 1, 1, 0, 1]

Напишите программу, которая расширяет список main элементами остальных списков, выведите итоговый список, а также выведите количество невыполненных задач.

Результат работы программы:

Общий список задач: [1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1]
Кол-во невыполненных задач: 10

**Задача 2. Вредоносное ПО**
Гера решил попрактиковаться в программировании и захотел написать небольшой скрипт, который после двух сообщений отправляет ещё одно на основе первых двух.

Пользователь вводит две строки. В каждой из них есть какое-то количество специальных символов ! и ?. Напишите программу, которая считает количество этих символов отдельно в первой строке и отдельно во второй. Если в первой строке их больше, чем во второй, то на экран выводится первая строчка, объединённая со второй, а иначе — вторая с первой. При равном количестве символов в строках выводится «Ой».

Пример 1:
Первое сообщение: Привет!
Второе сообщение: Как дела? Что делаешь?
Третье сообщение: Как дела? Что делаешь? Привет!

Пример 2:
Первое сообщение: Хм!!
Второе сообщение: ?
Третье сообщение: Хм!!?

**Задача 3. Пакеты**
При работе с сервером мы кодируем сообщение и отправляем его в виде пакетов информации. Их количество равно N. Допустим, каждый пакет содержит четыре числа, каждое из которых равно нулю или единице. Эти числа называются битами. Иногда в кодировке сообщения встречаются ошибки, и в пакете эта ошибка обозначается числом -1. Если таких ошибок не больше одной, то этот пакет мы целиком добавляем в список для декодирования, а иначе отбрасываем.

Напишите программу, которая будет обрабатывать полученные пакеты и выведет на экран итоговое сообщение для декодирования, а также количество ошибок в нём и количество необработанных пакетов.

Пример:
Кол-во пакетов: 3

Пакет номер 1
1 бит: 1
2 бит: 0
3 бит: -1
4 бит: 1

Пакет номер 2
1 бит: -1
2 бит: -1
3 бит: 1
4 бит: 1
Много ошибок в пакете.

Пакет номер 3
1 бит: 0
2 бит: 1
3 бит: 1
4 бит: 1

Полученное сообщение: [1, 0, -1, 1, 0, 1, 1, 1]
Кол-во ошибок в сообщении: 1
Кол-во потерянных пакетов: 1

2022-09-07 08:49 UTC, AlexandraPoturaeva commented
**16.4 Вложенные списки**

**Задача 1. Матрица**
Дан вот такой список со списками:
matrix = [[1, 2 ,3], [4, 5, 6], [7, 8, 9]]
Реализуйте программу, которая выводит элементы этого списка в виде привычной нам матрицы.

Результат работы программы:
1 2 3
4 5 6
7 8 9

**Задача 2. Олимпиада**
В олимпиаде по программированию участвует N человек, в списке участников они обозначаются под номерами 1, 2, 3, 4 и так далее до N. Эти участники поделены на команды по K человек.

Напишите программу, которая принимает на вход количество участников и количество человек в каждой команде, затем генерирует список таких команд и выводит его на экран. 

Обеспечьте контроль ввода: в каждой команде должно быть ровно по K человек.

Пример 1:
Кол-во участников: 12
Кол-во человек в команде: 4

Общий список команд: [[1, 2 ,3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

Пример 2:
Кол-во участников: 12
Кол-во человек в команде: 5

12 участников невозможно поделить на команды по 5 человек!

**Задача 3. Лавка**
В небольшой фруктовой лавке у каждого фрукта есть название и цена. Эта информация хранится в одном большом списке, вот так:

goods = [["яблоки", 50], ["апельсины", 190], ["груши", 100], ["нектарины", 200], ["бананы", 77]]

Недавно в лавку привезли новый fruit_name по цене price, а после этого случилось ужасное: повысили налоги. А значит, повысились и цены на фрукты, на целых 8%!

Реализуйте код, который добавляет в список goods ещё один список с новым фруктом и ценой (это запрашивается у пользователя), а затем увеличивает цены всех фруктов на 8%.

Пример:
Текущий ассортимент: [["яблоки", 50], ["апельсины", 190], ["груши", 100], ["нектарины", 200], ["бананы", 77]]
Новый фрукт: абрикосы
Цена: 150

Новый ассортимент: [["яблоки", 50], ["апельсины", 190], ["груши", 100], ["нектарины", 200], ["бананы", 77], ["абрикосы", 150]]

Новый ассортимент с увел. ценой: [['яблоки', 54.0], ['апельсины', 205.2], ['груши', 108.0], ['нектарины', 216.0], ['бананы', 83.16], ['абрикосы', 162.0]]

2022-09-14 11:06 UTC, AlexandraPoturaeva commented
**Задача 1. Страшный код**
Что нужно сделать

Вашему другу, который тоже начал изучать Python, преподаватель дал такую задачу: есть три списка — основной и два побочных. В основном лежат элементы [1, 5, 3], а в побочных — [1, 5, 1, 5] и [1, 3, 1, 5, 3, 3] соответственно. 

Первый побочный закидывается в основной, там считается количество цифр 5, количество выводится на экран, и затем они удаляются из основного списка. После этого в основной закидывается второй побочный список, там считается количество цифр 3 и выводится на экран. В конце также выводится и сам список.

Из интереса вы попросили вашего друга показать код его программы и поняли, что сделали это не зря — то, что вы увидели, повергло вас в шок и ужас. Вот сам код:

a = [1, 5, 3]
b = [1, 5, 1, 5]
c = [1, 3, 1, 5, 3, 3]
for i in b:
    a.append(i)
t = 0
for i in a:
    if i == 5:
        t += 1
print(t)
d = []
for i in a:
    if i != 5:
        d.append(i)
for i in c:
    d.append(i)
t = 0
for i in d:
    if i == 3:
        t += 1
print(t)
print(d)

Используя знания о методах списков, а также о стиле программирования, помогите другу переписать программу. Не используйте дополнительные списки.

Результат работы программы:

Кол-во цифр 5 при первом объединении: 3

Кол-во цифр 3 при втором объединении: 4

Итоговый список: [1, 3, 1, 1, 1, 3, 1, 5, 3, 3]

**Задача 2. Шеренга**
Что нужно сделать

Два класса стоят в две отдельные шеренги. В каждом классе ученики выстроены по росту (по возрастанию): в одном классе от 160 см до 176 см с шагом 2, во втором классе — от 162 см до 180 см с шагом 3. Спустя какое-то время два класса объединяют в одну шеренгу и тоже выстраивают их по возрастанию.

Напишите программу, которая генерирует списки роста для каждого в классе, затем объединяет их в один список и сортирует его в порядке возрастания. Выведите отсортированный список на экран.

Формат вывода ответа:

Отсортированный список учеников: [160, 162, …]



Что оценивается

Результат вычислений корректен.
Формат вывода соответствует указанному в задаче.

Сортировка описана в отдельной функции.
Переменные и функции имеют значащие имена, не только a, b, c, d (подробнее об этом в видео 2.3).


Задача 3. Детали
Что нужно сделать

В базе данных магазина всякой всячины хранится список названий деталей и их стоимостей:

shop = [['каретка', 1200], ['шатун', 1000], ['седло', 300], ['педаль', 100], ['седло', 1500], ['рама', 12000], ['обод', 2000], ['шатун', 200], ['седло', 2700]]
Продавец решил, что считать количество и стоимость деталей вручную не очень удобно, поэтому решил попросить помощи у программиста, чтобы оптимизировать этот процесс.

Напишите программу, которая запрашивает у пользователя деталь, считает их количество, а также общую стоимость.

 

Пример:

Название детали: седло

Кол-во деталей — 3  

Общая стоимость — 4500

**Задача 4. Вечеринка**
Что нужно сделать

В честь своего дня рождения Артём решил закатить вечеринку у себя на даче. Он не стал рассылать приглашения, а просто сообщил всем: «Если хотите — приходите и своих друзей тоже зовите». В ходе вечеринки люди приходили и уходили, ночевать остались не все. К тому же и сама дача не резиновая — на ней помещается всего шесть человек.

Дан изначальный список гостей — имена тех, кто пришёл к началу:

guests = [‘Петя’, ‘Ваня’, ‘Саша’, ‘Лиза’, ‘Катя’]
Напишите программу, которая спрашивает у пользователя, ушёл человек или пришёл новый гость, и, исходя из ответа, добавляет в список или удаляет из него нужное имя. При этом гостей может быть не больше шести. Имена запрашиваются до тех пор, пока пользователь не введёт сообщение «Пора спать».

Пример:
Сейчас на вечеринке 5 человек: [‘Петя’, ‘Ваня’, ‘Саша’, ‘Лиза’, ‘Катя’]
Гость пришёл или ушёл? пришёл
Имя гостя: Алекс
Привет, Алекс!

Сейчас на вечеринке 6 человек: [‘Петя’, ‘Ваня’, ‘Саша’, ‘Лиза’, ‘Катя’, ‘Алекс’]
Гость пришёл или ушёл? пришёл
Имя гостя: Гоша
Прости, Гоша, но мест нет.

Сейчас на вечеринке 6 человек: [‘Петя’, ‘Ваня’, ‘Саша’, ‘Лиза’, ‘Катя’, ‘Алекс’]
Гость пришёл или ушёл? ушёл
Имя гостя: Ваня
Пока, Ваня!

Сейчас на вечеринке 5 человек: [‘Петя’, ‘Саша’, ‘Лиза’, ‘Катя’, ‘Алекс’]
Гость пришёл или ушёл? Пора спать
Вечеринка закончилась, все легли спать.

Задача 5. Песни
Что нужно сделать

Мы пишем приложение для удобного прослушивания музыки. У Вани есть список из девяти песен группы Depeche Mode. Каждая песня состоит из названия и продолжительности с точностью до долей минут:

violator_songs = [
    ['World in My Eyes', 4,86],
    ['Sweetest Perfection', 4,43],
    ['Personal Jesus', 4,56],
    ['Halo', 4,9],
    ['Waiting for the Night', 6,07],
    ['Enjoy the Silence', 4,20],
    ['Policy of Truth', 4,76],
    ['Blue Dress', 4,29],
    ['Clean', 5,83]
]
 
Из этого списка Ваня хочет выбрать N песен и закинуть их в особый плейлист с другими треками. И при этом ему важно, сколько времени в сумме эти N песен будут звучать.
Напишите программу, которая запрашивает у пользователя количество песен из списка и затем названия этих песен, а на экран выводит общее время их звучания.

Пример:
Сколько песен выбрать? 3
Название 1-й песни: Halo
Название 2-й песни: Enjoy the Silence
Название 3-й песни: Clean

Общее время звучания песен: 14,93 минуты

**Задача 6. Уникальные элементы**
Что нужно сделать

Даны два списка целых чисел, оба списка заполняются с клавиатуры. В первый список вводится три числа, во второй — семь чисел. Напишите программу, которая запрашивает у пользователя эти числа, затем расширяет первый список элементами второго и после этого оставляет в первом списке только уникальные элементы, то есть удаляет лишние повторы чисел. Условный оператор использовать нельзя.

Пример:
Введите 1-е число для первого списка: 1
Введите 2-е число для первого списка: 2
Введите 3-е число для первого списка: 3

Введите 1-е число для второго списка: 2
Введите 2-е число для второго списка: 4
Введите 3-е число для второго списка: 6
Введите 4-е число для второго списка: 3
Введите 5-е число для второго списка: 3
Введите 6-е число для второго списка: 2
Введите 7-е число для второго списка: 1

Первый список: [1, 2, 3]
Второй список: [2, 4, 6, 3, 3, 2, 1]

Новый первый список с уникальными элементами: [4, 6, 3, 2, 1]

**Задача 7. Ролики**
Что нужно сделать

Частная контора даёт в прокат ролики самых разных размеров. Человек может надеть ролики любого размера, которые не меньше размера его ноги. 
Пользователь вводит два списка размеров: N размеров коньков и K размеров ног людей. Реализуйте код, который определяет, какое наибольшее число человек сможет одновременно взять ролики и пойти покататься. 

Пример:

Кол-во коньков: 4
Размер 1-й пары: 41
Размер 2-й пары: 40
Размер 3-й пары: 39
Размер 4-й пары: 42

Кол-во людей: 3
Размер ноги 1-го человека: 42
Размер ноги 2-го человека: 41
Размер ноги 3-го человека: 42

Наибольшее кол-во людей, которые могут взять ролики: 2

**Задача 8. Считалка**
Что нужно сделать

N человек, пронумерованных числами от 1 до N, стоят в кругу. Они начинают играть в считалку на выбывание, где каждый K-й по счёту человек выбывает из круга, после чего счёт продолжается со следующего за ним человека.

На вход подаётся количество человек N и номер K. Напишите программу, которая выводит число от 1 до N — это номер человека, который останется в кругу последним.

Пример:
Кол-во человек: 5
Какое число в считалке? 7
Значит, выбывает каждый 7-й человек

Текущий круг людей: [1, 2, 3, 4, 5]
Начало счёта с номера 1
Выбывает человек под номером 2

Текущий круг людей: [1, 3, 4, 5]
Начало счёта с номера 3
Выбывает человек под номером 5

Текущий круг людей: [1, 3, 4]
Начало счёта с номера 1
Выбывает человек под номером 1

Текущий круг людей: [3, 4]
Начало счёта с номера 3
Выбывает человек под номером 3

Остался человек под номером 4

**Задача 9. Друзья**
Что нужно сделать

N друзей постоянно берут в долг друг у друга деньги. В какой-то момент им надоело забывать, кто, кому и сколько должен, и они придумали систему долговых расписок. И, чтобы начать новый год «с чистого листа», друзья решили оплатить все долговые расписк [...]

2022-09-18 09:51 UTC, dimastaja requested changes

2022-09-18 09:51 UTC, dimastaja commented on 16_lists-methods.py
> +# shop = [['каретка', 1200], ['шатун', 1000], ['седло', 300], ['педаль', 100], ['седло', 1500], ['рама', 12000], ['обод', 2000], ['шатун', 200], ['седло', 2700]]
Такое нужно форматировать, читать неудобно https://dvmn.org/encyclopedia/clean_code/python_basics_formatting/ 
 
```suggestion
# shop = [
     ['каретка', 1200], 
     ['шатун', 1000], 
     ['седло', 300],
     ...
]     
```

2022-09-18 09:51 UTC, dimastaja commented on 16_lists-methods.py
> +#
эти if action=='' тоже надо заменить на switch или match (смотря, что лучше подходит)

2022-09-18 10:34 UTC, AlexandraPoturaeva commented on 15_lists.py
> +
Просьба удалить лишние пробелы

2022-09-18 12:18 UTC, dimastaja requested changes

2022-09-18 12:18 UTC, dimastaja commented on 16_lists-methods.py
> +# ]
вот это норм, кстати

2022-09-18 12:18 UTC, dimastaja commented on 16_lists-methods.py
> +#
Зачем это?

2022-09-18 12:18 UTC, dimastaja commented on 16_lists-methods.py
> +#         list_1.remove(num_to_remove)
Очень сложно.

2022-09-18 12:18 UTC, dimastaja commented on 16_lists-methods.py
> +#     num_to_remove_index = (start_num_index + count_num - 1) % len(pers_list)
делать четыре принта подряд - ну сложно очень читать. Добавляй лучше просто `\n`

2022-09-18 19:23 UTC, merged

2022-09-22 09:38 UTC, AlexandraPoturaeva commented on 16_lists-methods.py
> +#
По условиям задачи при её выполнении нельзя использовать условный оператор, для этого и был использован данный алгоритм.  Добавила второй метод решения с использованием set. При использовании set меняется порядок числе - в примере к задаче порядок не меняется, так что это не совсем тот путь.

2022-09-22 09:41 UTC, AlexandraPoturaeva commented on 16_lists-methods.py
> +#         list_1.remove(num_to_remove)
см. комментарий выше, проще способа не придумалось